name: STATIC WEBSITE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  deployToStage:     
    runs-on: ubuntu-latest
    needs: build
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Heroku login credentials
      run: |
        touch ~/.netrc
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_EMAIL" >> ~/.netrc
        echo "  password $HEROKU_API_KEY" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login $HEROKU_EMAIL" >> ~/.netrc
        echo "  password $HEROKU_API_KEY" >> ~/.netrc
        cat ~/.netrc
        
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    - name: Add Heroku remote
      run: |
        heroku git:remote --app vihaar

    - name: Push to Heroku staging
      run: |
        git add .
        git commit -m "Added with .env"
        git push heroku master -f
